name: Google Chat Broken Main Notification
on:
  check_suite:
    types:
      - completed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Google Chat Notification
        if: ${{ github.event.check_suite.conclusion == 'failure' }}
        run: |
            curl --location --request POST '${{ secrets.RELEASES_WEBHOOK }}' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "text": "Main is broken! @ ${{github.event.check_suite.created_at}} see <${{github.event.check_suite.url}}|[github]>"
            }'
